# Evelyn MFG::COMPDevOps
# Author: ya boi, nate.
# Date Created: 20240704
# use 'docker compose' to run a portable suite of CI tools:
# portainer: docker monitor for prod
# uptime-kuma: uptime monitor
# apache guac: team viewer via browser

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data

volumes:
  portainer-data:
  uptime-kuma-data:

networks:
  jenkins_network:
    driver: bridge

