# Evelyn MFG::COMPDevOps
# Author: ya boi, nate.
# Date Created: 20240704
# use 'docker compose' to run a portable version of the CI stack:
# Jenkins: CI server.
# Docker: Container runtime
# Selenium: E2E framework

services:
  jenkins:
    image: theautonater801/jenkins:v1
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8085:8085"
      - "50000:50000"
      - "36953:36953"
    networks:
      - jenkins_network
    restart: unless-stopped

  docker:
    image: docker
    container_name: docker
    privileged: true
    volumes:
      - docker-data:/var/lib/docker
    networks:
      - jenkins_network

# no matching manifest for linux/arm64/v8.
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - DISPLAY=:99.0
    networks:
      - jenkins_network
    ports:
      - "4444:4444"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data

  guacamole:
    image: guacamole/guacamole
    restart: always
    ports:
      - "8080:8080"

    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: compadmin
      MYSQL_PASSWORD: 18c0mp4ni0n31
      MYSQL_ROOT_PASSWORD: 18c0mp4ni0n31
    depends_on:
      - guacd
      - db

  guacd:
    image: guacamole/guacd
    restart: always

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: compadmin
      MYSQL_PASSWORD: 18c0mp4ni0n31
      MYSQL_ROOT_PASSWORD: 18c0mp4ni0n31
    volumes:
      - guac-db-data:/var/lib/mysql

volumes:
  jenkins-data:
  docker-data:
  portainer-data:
  uptime-kuma-data:
  guac-db-data:

networks:
  jenkins_network:
    driver: bridge

