# Evelyn MFG::COMPDevOps
# Author: ya boi, nate.
# Date Created: 20240704
# use 'docker compose' to run a portable version of the CI stack:
# Jenkins: CI server.
# Docker: Container runtime
# this is DinD btw, so don't use it on mac.

services:
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8080:8080"
      - "50000:50000"
      - "36953:36953"
    networks:
      - jenkins_network
    restart: unless-stopped

  docker:
    image: docker
    container_name: docker
    privileged: true
    user: root
    volumes:
      - docker-data:/var/lib/docker
    networks:
      - jenkins_network

volumes:
  jenkins-data:
  docker-data:

networks:
  jenkins_network:
    driver: bridge

