# Evelyn MFG::COMPDevOps
# Author: ya boi, nate.
# Date Created: 20240704
# use 'docker compose' to run a portable version of the CI stack:
# Jenkins: CI server.
# Docker: Container runtime
# Selenium: E2E framework

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8080:8080"
      - "50000:50000"
      - "36953:36953"
    networks:
      - jenkins_network
    restart: unless-stopped

  docker:
    image: docker
    container_name: docker
    privileged: true
    volumes:
      - docker-data:/var/lib/docker
    networks:
      - jenkins_network

# no matching manifest for linux/arm64/v8. wont work on mac's fancy bullshit.
#  selenium:
#    image: selenium/standalone-chrome
#    container_name: selenium
#    environment:
#      - SCREEN_WIDTH=1920
#      - SCREEN_HEIGHT=1080
#      - SCREEN_DEPTH=24
#      - DISPLAY=:99.0
#    networks:
#      - jenkins_network
#    ports:
#      - "4444:4444"

volumes:
  jenkins-data:
  docker-data:

networks:
  jenkins_network:
    driver: bridge

