# Evelyn MFG::COMPDevOps
# Author: ya boi, nate.
# Date Created: 20240704
# use 'docker compose' to run a portable suite of CI tools:
# portainer: docker monitor for prod
# uptime-kuma: uptime monitor
# apache guac: team viewer via browser

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data

  guacamole:
    image: guacamole/guacamole
    restart: always
    ports:
      - "8083:8083"

    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: compadmin
      MYSQL_PASSWORD: 18c0mp4ni0n31
      MYSQL_ROOT_PASSWORD: 18c0mp4ni0n31
    depends_on:
      - guacd
      - db

  guacd:
    image: guacamole/guacd
    restart: always

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: compadmin
      MYSQL_PASSWORD: 18c0mp4ni0n31
      MYSQL_ROOT_PASSWORD: 18c0mp4ni0n31
    volumes:
      - guac-db-data:/var/lib/mysql

volumes:
  portainer-data:
  uptime-kuma-data:
  guac-db-data:

networks:
  jenkins_network:
    driver: bridge

