# Dockerfile for custom Jenkins image
FROM jenkins/jenkins:lts

USER root
RUN groupadd -g 999 docker
RUN usermod -aG docker jenkins
RUN chown root:docker /var/run/docker.sock

USER jenkins

# tidbit: if you dont override the entrypoint or cmd, the base image will start normally.