# Evelyn MFG::COMPDevOps
# Author: ya boi, nate.
# Date Created: 20240711
# use 'docker compose' to run an instance of uptime-kuma:
# uptime-kuma: uptime monitor with great integrations & a snazzy UI.

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data

volumes:
  uptime-kuma-data: